# Disable metrics
opt_out_usage

# Configuration
private_keychain_name = "fastlane_keychain"
private_keychain_password = "does-not-matter"

default_platform(:ios)

platform :ios do

  desc "Creates a private Keychain. This is needed so that the Beta can be created by a GitHub Action."
  private_lane :create_private_keychain do
    # See: https://medium.com/well-red/github-actions-fastlane-ios-1f6d43cce726
    create_keychain(
      name: private_keychain_name,
      password: private_keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
  end

  desc "Performs basic integration checks to be run before merging"
  lane :pull_request_checks do
    run_tests(
      project: "Go Map!!.xcodeproj",
      scheme: "GoMapTests"
    )
  end

  desc "Re-generates the app icon from the base app_icon.png in the fastlane metadata directory"
  lane :regenerate_app_icon do
    appicon(
      appicon_devices: [:ipad, :iphone, :ios_marketing],
      appicon_path: "../Images.xcassets"
    )
  end

  desc "Builds and uploads a new TestFlight Beta release."
  lane :beta do
    UI.message("Preparing new TestFlight release...")

    # Make sure that all tests run successfully.
    pull_request_checks

    create_private_keychain

    # Bump the build number and the version.
    increment_build_number
    increment_version_number(bump_type: 'patch')
    commit_version_bump(
      xcodeproj: './Go Map!!.xcodeproj',
      message: 'Bump build number and version'
    )
  end

end
