# Disable metrics
opt_out_usage

default_platform(:ios)

platform :ios do

  desc "Performs basic integration checks to be run before merging"
  lane :pull_request_checks do
    run_tests(
      project: "Go Map!!.xcodeproj",
      scheme: "GoMapTests"
    )
  end

end
